spring:
  cloud:
    gcp:
      storage:
        enabled: false
        project-id: ""
        bucket: ""

app.melon.static.host: ""
---
spring:
  config:
    activate:
      on-profile: local, test

app.melon.static.host: https://sandbox-fan-static.melon.com
---
spring:
  config:
    activate:
      on-profile: sandbox
  cloud:
    gcp:
      storage:
        enabled: true
        project-id: "dev-melon-fan-platform-project"
        bucket: "dev-melon-fan-lounge-static-resources-bucket"
app.melon.static.host: https://sandbox-fan-static.melon.com
---
spring:
  config:
    activate:
      on-profile: cbt, prod
  cloud:
    gcp:
      storage:
        enabled: true
        project-id: "prod-melon-fanconnect-project"
        bucket: "prod-melon-fan-lounge-static-resources-bucket"
app.melon.static.host: https://cbt-fan-static.melon.com
