spring:
  config:
    activate:
      on-profile: test
    import: application-context.yaml
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true

logging:
  level:
    org.hibernate:
      #stat: DEBUG
      SQL: DEBUG
