spring:
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        generate_statistics: true
        session.events.log.LOG_QUERY_SLOWER_THAN_MS: 10
        default_batch_fetch_size: 500

---
spring:
  config:
    activate:
      on-profile: local, test
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fan_md;MODE=MySQL;
    username: sa
    password:

---
spring:
  config:
    activate:
      on-profile: sandbox
  cloud:
    gcp:
      sql:
        database-name: dev-melon-fan-platform-kr-mysql
        instance-connection-name: dev-melon-fan-platform-project:asia-northeast3:dev-melon-fan-platform-kr-mysql
  data:
    redis:
      host: 10.157.72.3
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sandbox-fan-lounge-mydb.kakaoent.io:3306/fan_md
    username: ${sm://spring-datasource-username}
    password: ${sm://spring-datasource-password}