spring:
  config:
    activate:
      on-profile: local, test
  cloud:
    gcp:
      core:
        enabled: false
      logging:
        enabled: false
      secretmanager:
        enabled: false
---
spring:
  config:
    activate:
      on-profile: sandbox, cbt, prod
    import: sm://
