spring:
  config:
    import:
      - application-context-data.yaml
      - application-context-logging.yaml
      - application-context-gcp.yaml

---
spring:
  config:
    activate:
      on-profile: local

