logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.hibernate:
      stat: DEBUG
      SQL: DEBUG
---
spring:
  config:
    activate:
      on-profile: sandbox
---
spring:
  config:
    activate:
      on-profile: cbt
---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    org.hibernate:
      stat: INFO
      SQL: INFO
      engine.internal: WARN
      stat.internal: WARN