server:
  shutdown: graceful
  error.whitelabel.enabled: false
spring:
  profiles:
    default: local
  application:
    name: melon-fan-md
  config:
    import:
      - application-context.yaml
      - application-external.yaml
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 21MB
  jackson:
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: sandbox
  jpa:
    hibernate:
      ddl-auto: create